version: "3"
services:
  front:
    image: node:14
    volumes:
      - ./front:/usr/src
      - front_modules:/usr/src/node_modules #node_modulesはコンテナ内部で用意します
    working_dir: "/usr/src"
    command: sh -c "yarn install && yarn start"
    ports:
      - "80:3000"
    restart: always
  api:
    build:
      context: ./api
    volumes:
      - ./api/:/usr/src/
    working_dir: "/usr/src"
    ports:
      - "8000:80"
    environment:
      CLIENT_ORIGIN_URL: "http://localhost"
      RDS_HOSTNAME: db
      RDS_USERNAME: root
      RDS_PASSWORD: docker
      RDS_DB_NAME: test_db
      RAKUTEN_APP_ID: $RAKUTEN_APP_ID
    command: sh -c 'flask db upgrade ; python app.py'
    depends_on:
      - db
    restart: always
  db:
    platform: linux/x86_64 # M1チップ対応のため追記
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: docker
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/data:/var/lib/mysql #データ永続化
      - ./db/sql:/docker-entrypoint-initdb.d #起動時sqlフォルダ内のsqlファイルを実行
    restart: always
  phpmyadmin:
    image: phpmyadmin #fpmやalpineタグは別途httpサーバが必要
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=docker
    ports:
      - 8080:80
    volumes:
      - "./phpmyadmin:/sessions"
    depends_on:
      - db
    restart: always
volumes:
  front_modules:
  api_modules:
