"""added attributes necessary for login to user

Revision ID: aa3b1491c079
Revises: 1c1ba8aa22b8
Create Date: 2021-09-14 06:41:50.904815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3b1491c079'
down_revision = '1c1ba8aa22b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
