POST http://localhost:8000/login HTTP/1.1
content-type: application/json

{
    "username": "Yasoob",
    "password": "strongpassword"
}

###

GET http://localhost:8000/api/protected HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MzE2MDU5NjQsImV4cCI6MTYzMTY5MjM2NCwianRpIjoiNTZmYTUzZDAtZmMzOC00M2UwLWFhOGQtZjM1ZWI2M2JlYmJjIiwiaWQiOjEsInJscyI6ImFkbWluIiwicmZfZXhwIjoxNjM0MTk3OTY0fQ.zXC3bujxwYQZahHKMFQe2Dv1vhvkk0HLw8I6YxSk-VQ

###
# You have to set RAKUTEN_APP_ID in your vscode/settings.json
# https://dev.classmethod.jp/articles/vscode-rest-client-is-good/
# test product Ids
# sorara:10001376
# jmei:10004611
# sorara:10003082
GET https://app.rakuten.co.jp/services/api/IchibaItem/Search/20170706?applicationId={{RAKUTEN_APP_ID}}&keyword=%E7%A6%8F%E8%A2%8B&sort=standard HTTP/1.1
